[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "gpie-ptychography"
version = "0.1.0"
dependencies = [
    "numpy>=2.2.6",
]

[tool.setuptools.packages.find]
where = ["."]